### ISSUE TITLE
Feature Request: unfilled circle/rectangle methods

### ISSUE THREAD

**Issue by stulentsev** [kswaldemar/rewind-viewer#39]
Sometimes we need just the border, not the fill.

**Comment by kswaldemar** [comment]
Well, I found that it is not very often used features.
If you need rectangle, solution is pretty straightforward - just use 4 lines.
When it comes to circle it's more complicated, because for that feature you need to extend circle shader.
I wouldn't like to do that, because there is refactoring and draw call optimizations should be performed before. Which is more time consuming. So I think that feature has no chance for this year.

Which problem do you want to solve? Maybe you could use layers and transparent primitives for that?

**Comment by stulentsev** [comment]
> Which problem do you want to solve?

Visualizing effective vision ranges, for instance (debug nuke calculations). Filled circles, with however low opacity, still completely hide everything under them (when we do that for tightly packed formations).

**Comment by MelnikovIG** [comment]
It make sense, especially for final rounds to draw vision ranges.

**Comment by kswaldemar** [comment]
Support for unfilled circles and rectangles now in `develop` branch starting from 6c7ea486
Will be in next release
